In [1]:
for i in range(5):
    print (i)

0
1
2
3
4


In [2]:
for i in range(5, 10):
    print (i)

5
6
7
8
9


In [3]:
for i in range(5, 10, 2):
    print (i)

5
7
9


In [4]:
for i in range(10, 5):
    print (i)

In [9]:
for i in range(10, 5, -1):
    print (i)

10
9
8
7
6


In [6]:
x = [
    [1, 2, 3],
    [4, 5, 6]
]

# Select the second column from x
second_column = [row[1] for row in x]
second_column

[2, 5]

In [61]:
import numpy as np
x = np.array([
    [1,  2,  3,  4,  5],
    [6,  7,  8,  9,  10,],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20]
])

z = 2 * np.array([
    [1,  2,  3,  4,  5],
    [6,  7,  8,  9,  10,],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20]
])
y = x[1:3, 1:4]
print(y)
y

[[ 7  8  9]
 [12 13 14]]


array([[ 7,  8,  9],
       [12, 13, 14]])

In [62]:
x = 20 * x
z

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

In [64]:
a = input("input a number: ")

In [ ]:
[0, ] * 3 * 4

[0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2]

In [ ]:

def prettyPrint(A):
    L = 2 * A - 1
    matrix = [[0] * L for _ in range (L)]
    for r in range(L):
        for c in range(L):
            matrix[r][c] = A - (min(r, L - r - 1, c, L - c - 1))
                
    print

    return matrix

prettyPrint(3)

[[3, 3, 3, 3, 3], [3, 2, 2, 2, 3], [3, 2, 1, 2, 3], [3, 2, 2, 2, 3], [3, 3, 3, 3, 3]]


[[3, 3, 3, 3, 3],
 [3, 2, 2, 2, 3],
 [3, 2, 1, 2, 3],
 [3, 2, 2, 2, 3],
 [3, 3, 3, 3, 3]]

In [ ]:
a, b = 0, 1
c = [5, 15]
a, b = a, b + c[1], c[1]

ValueError: too many values to unpack (expected 2)

In [95]:
def spiralOrder(A):
    step_list = [
        [0, 1],
        [1, 0],
        [0, -1],
        [-1, 0]
    ]
    step_stat = 0
    
    ans = []
    
    w = len(A[0])
    h = len(A)
    
    B = [[0] * w for _ in range(h)]
    
    r = 0
    c = 0
    for _ in range(w * h):
        ans.append(A[r][c])
        B[r][c] = 1
        next_step = step_list[step_stat]
        if (
            r + next_step[0] >= h 
            or r + next_step[0] < 0 
            or c + next_step[1] >= w 
            or c + next_step[1] < 0 
            or B[r + next_step[0]][c + next_step[1]] == 1
        ):
            step_stat = (step_stat + 1) % 4
        
        print("r = ", r, " c = ", c, " step_stat = ", step_stat)
        r = r + step_list[step_stat][0]
        c = c + step_list[step_stat][1]
        print("r = ", r, " c = ", c, " step_stat = ", step_stat)
        
    return ans

A = [
    [ 1, 2, 3 ],
    [ 4, 5, 6 ],
    [ 7, 8, 9 ]
]

print(spiralOrder(A))

r =  0  c =  0  step_stat =  0
r =  0  c =  1  step_stat =  0
r =  0  c =  1  step_stat =  0
r =  0  c =  2  step_stat =  0
r =  0  c =  2  step_stat =  1
r =  1  c =  2  step_stat =  1
r =  1  c =  2  step_stat =  1
r =  2  c =  2  step_stat =  1
r =  2  c =  2  step_stat =  2
r =  2  c =  1  step_stat =  2
r =  2  c =  1  step_stat =  2
r =  2  c =  0  step_stat =  2
r =  2  c =  0  step_stat =  3
r =  1  c =  0  step_stat =  3
r =  1  c =  0  step_stat =  0
r =  1  c =  1  step_stat =  0
r =  1  c =  1  step_stat =  1
r =  2  c =  1  step_stat =  1
[1, 2, 3, 6, 9, 8, 7, 4, 5]


In [104]:
qwe = 1

match qwe:
    case 1:
        print("one")
    case "2":
        print("two")
    case 1:
        print("three")
    case _:
        print("other")


one


In [110]:
dictionary = {
    "one": 1,
    "two": 2,
    "three": 3
}

print(dictionary["two"])

2


In [2]:
for x in range(5):
    x += 100
    print(x)

100
101
102
103
104


In [ ]:
x = [1, 2, 3, 4, 5]

len(x)

AttributeError: 'list' object has no attribute 'len'